apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-ingress.yaml

images:
  - name: shopcloud-backend
    newName: shopcloud-backend
    newTag: latest
  - name: shopcloud-frontend
    newName: shopcloud-frontend
    newTag: latest
